-- Tabela USUARIO
CREATE TABLE USUARIO (
    USUARIO_ID INT PRIMARY KEY,
    CPF VARCHAR(20),
    DATA_DE_NASCIMENTO DATE,
    RG VARCHAR(20),
    EMAIL VARCHAR(255),
    CHAVE_PIX VARCHAR(255),
    NOME VARCHAR(255),
    RATING INT,
    SENHA VARCHAR(255)
);

-- Tabela AVALIACAO
CREATE TABLE AVALIACAO (
    AVALIACAO_ID INT PRIMARY KEY,
    AVALIADO_ID INT,
    AVALIADOR_ID INT,
    STATUS VARCHAR(50),
    ESTRELA INT,
    DATA DATE,
    FOREIGN KEY (AVALIADO_ID) REFERENCES USUARIO(USUARIO_ID),
    FOREIGN KEY (AVALIADOR_ID) REFERENCES USUARIO(USUARIO_ID)
);

-- Tabela DENUNCIA
CREATE TABLE DENUNCIA (
    DENUNCIA_ID INT PRIMARY KEY,
    DENUNCIADO_ID INT,
    DENUNCIANTE_ID INT,
    STATUS VARCHAR(50),
    MOTIVO TEXT,
    DATA DATE,
    FOREIGN KEY (DENUNCIADO_ID) REFERENCES USUARIO(USUARIO_ID),
    FOREIGN KEY (DENUNCIANTE_ID) REFERENCES USUARIO(USUARIO_ID)
);

-- Tabela NOTIFICACAO
CREATE TABLE NOTIFICACAO (
    NOTIFICACAO_ID INT PRIMARY KEY,
    ENVIO_ID INT,
    RECEBIMENTO_ID INT,
    STATUS VARCHAR(50),
    DATA DATE,
    TEXTO TEXT,
    FOREIGN KEY (ENVIO_ID) REFERENCES USUARIO(USUARIO_ID),
    FOREIGN KEY (RECEBIMENTO_ID) REFERENCES USUARIO(USUARIO_ID)
);

-- Tabela INGRESSO
CREATE TABLE INGRESSO (
    INGRESSO_ID INT PRIMARY KEY,
    USUARIO_ID INT,
    STATUS VARCHAR(50),
    IMAGEM VARCHAR(255),
    PRECO DECIMAL(10, 2),
    DESCRICAO TEXT,
    DATA DATE,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

-- Tabela VENDA
CREATE TABLE VENDA (
    VENDA_ID INT PRIMARY KEY,
    USUARIO_ID INT,
    INGRESSO_ID INT,
    DATA DATE,
    STATUS VARCHAR(50),
    TITULARIDADE VARCHAR(255),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
    FOREIGN KEY (INGRESSO_ID) REFERENCES INGRESSO(INGRESSO_ID)
);

-- Tabela COMPRA
CREATE TABLE COMPRA (
    COMPRA_ID INT PRIMARY KEY,
    USUARIO_ID INT,
    INGRESSO_ID INT,
    DATA DATE,
    STATUS VARCHAR(50),
    PAGAMENTO VARCHAR(255),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
    FOREIGN KEY (INGRESSO_ID) REFERENCES INGRESSO(INGRESSO_ID)
);
